services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ~/.cache/huggingface:/root/.cache/huggingface  # Map local cache to container
    networks:
      - default-net
    env_file:
    - .env
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - default-net
    restart: always
    env_file:
    - .env

  chroma-db:
    build:
      context: ./chroma
    container_name: chroma-db
    ports:
      - 5000:5000
    networks:
      - default-net
    volumes:
      - chroma-db:/chroma/database

networks:
  default-net:
    driver: bridge

volumes:
  chroma-db:
    driver: local
 

